- name: Configure Kubernetes Cluster and Host Instances
  hosts: all
  roles:
    - { role: jakoberpf.k3s, become: yes }
  tasks:
    - name: Allow tpc connections on multiple ports
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_ports:
          - 22 # teleport (master, worker)
          - "{{ ansible_port }}" # ssh (master, worker)
          # - 53 # local dns cache (master, worker)
          - 80 # http  (master, worker)
          # - 179 # calico (master, worker)
          - 443 # https (master, worker)
          # - 2378 # etcd (master)
          # - 2380 # etcd (master)
          # - 4240 # cilium health checks (master, worker)
          - 6443 # kubernetes api server (master)
          # - 8883 # netmaker
          # - 1888 # netmaker
          # - 10250 # kubelet (master, worker)
        jump: ACCEPT
        flush: true
      become: true
    # - name: Allow udp connections on relevant ports
    #   ansible.builtin.iptables:
    #     chain: INPUT
    #     protocol: udp
    #     destination_ports:
    #       - 53 # local dns cache (master, worker)
    #       - 8472 # VXLAN overlay (master, worker)
    #     jump: ACCEPT
    #     flush: true
    # - name: "[DEBUG] Save empty ruleset to disk so it will be reloaded on reboot"
    #   ansible.builtin.command: netfilter-persistent save
    - name: Fetch /etc/rancher/k3s/k3s.yaml
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: artifacts/k3s-{{ cluster_env }}.yaml
        flat: yes
      become: true
      run_once: true
